// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitStreamMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EmitStreamMessage'](arg1, arg2, arg3, arg4);
}

export function GetCtx() {
  return window['go']['main']['App']['GetCtx']();
}

export function GetDataDirectory() {
  return window['go']['main']['App']['GetDataDirectory']();
}

export function GrpcConnect(arg1) {
  return window['go']['main']['App']['GrpcConnect'](arg1);
}

export function GrpcDisconnect(arg1) {
  return window['go']['main']['App']['GrpcDisconnect'](arg1);
}

export function GrpcParseProtoFiles(arg1) {
  return window['go']['main']['App']['GrpcParseProtoFiles'](arg1);
}

export function GrpcSendMessage(arg1) {
  return window['go']['main']['App']['GrpcSendMessage'](arg1);
}

export function GrpcUseReflection(arg1, arg2) {
  return window['go']['main']['App']['GrpcUseReflection'](arg1, arg2);
}

export function KafkaConnect(arg1) {
  return window['go']['main']['App']['KafkaConnect'](arg1);
}

export function KafkaDisconnect(arg1) {
  return window['go']['main']['App']['KafkaDisconnect'](arg1);
}

export function KafkaListTopics(arg1) {
  return window['go']['main']['App']['KafkaListTopics'](arg1);
}

export function KafkaProduceMessage(arg1) {
  return window['go']['main']['App']['KafkaProduceMessage'](arg1);
}

export function KafkaStartConsumer(arg1) {
  return window['go']['main']['App']['KafkaStartConsumer'](arg1);
}

export function KafkaStopConsumer(arg1, arg2) {
  return window['go']['main']['App']['KafkaStopConsumer'](arg1, arg2);
}

export function LoadCollections() {
  return window['go']['main']['App']['LoadCollections']();
}

export function LoadEnvironments() {
  return window['go']['main']['App']['LoadEnvironments']();
}

export function LoadHistory() {
  return window['go']['main']['App']['LoadHistory']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function LoadWorkspaces() {
  return window['go']['main']['App']['LoadWorkspaces']();
}

export function SSEConnect(arg1) {
  return window['go']['main']['App']['SSEConnect'](arg1);
}

export function SSEDisconnect(arg1) {
  return window['go']['main']['App']['SSEDisconnect'](arg1);
}

export function SaveCollections(arg1) {
  return window['go']['main']['App']['SaveCollections'](arg1);
}

export function SaveEnvironments(arg1) {
  return window['go']['main']['App']['SaveEnvironments'](arg1);
}

export function SaveHistory(arg1) {
  return window['go']['main']['App']['SaveHistory'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveWorkspaces(arg1) {
  return window['go']['main']['App']['SaveWorkspaces'](arg1);
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function WebSocketConnect(arg1) {
  return window['go']['main']['App']['WebSocketConnect'](arg1);
}

export function WebSocketDisconnect(arg1) {
  return window['go']['main']['App']['WebSocketDisconnect'](arg1);
}

export function WebSocketSendMessage(arg1) {
  return window['go']['main']['App']['WebSocketSendMessage'](arg1);
}
