// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {backend} from '../models';

export function EmitStreamMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function GetCtx():Promise<context.Context>;

export function GetDataDirectory():Promise<string>;

export function GrpcConnect(arg1:backend.GrpcConnectRequest):Promise<string>;

export function GrpcDisconnect(arg1:string):Promise<void>;

export function GrpcParseProtoFiles(arg1:backend.ProtoFileUploadRequest):Promise<backend.ParsedProtoResponse>;

export function GrpcSendMessage(arg1:backend.GrpcSendMessageRequest):Promise<void>;

export function GrpcUseReflection(arg1:string,arg2:boolean):Promise<backend.ParsedProtoResponse>;

export function KafkaConnect(arg1:backend.KafkaConfig):Promise<string>;

export function KafkaDisconnect(arg1:string):Promise<void>;

export function KafkaListTopics(arg1:string):Promise<Array<backend.TopicInfo>>;

export function KafkaProduceMessage(arg1:backend.ProducerConfig):Promise<void>;

export function KafkaStartConsumer(arg1:backend.ConsumerConfig):Promise<string>;

export function KafkaStopConsumer(arg1:string,arg2:string):Promise<void>;

export function LoadCollections():Promise<Array<backend.Collection>>;

export function LoadEnvironments():Promise<Array<backend.Environment>>;

export function LoadHistory():Promise<Array<backend.HistoryItem>>;

export function LoadSettings():Promise<backend.Settings>;

export function LoadWorkspaces():Promise<Array<backend.Workspace>>;

export function SSEConnect(arg1:backend.SSEConnectRequest):Promise<string>;

export function SSEDisconnect(arg1:string):Promise<void>;

export function SaveCollections(arg1:Array<backend.Collection>):Promise<void>;

export function SaveEnvironments(arg1:Array<backend.Environment>):Promise<void>;

export function SaveHistory(arg1:Array<backend.HistoryItem>):Promise<void>;

export function SaveSettings(arg1:backend.Settings):Promise<void>;

export function SaveWorkspaces(arg1:Array<backend.Workspace>):Promise<void>;

export function SendRequest(arg1:backend.RequestData):Promise<backend.ResponseData>;

export function WebSocketConnect(arg1:backend.WebSocketConnectRequest):Promise<string>;

export function WebSocketDisconnect(arg1:string):Promise<void>;

export function WebSocketSendMessage(arg1:backend.WebSocketSendRequest):Promise<void>;
